### ISSUE TITLE
好像数据库挂了，没有数据。

### ISSUE THREAD

**Issue by tianlinzx** [liangwei0101/liang_flutter_demo#1]
好像数据库挂了，没有数据。
http://101.132.124.171:8000/about

**Comment by liangwei0101** [comment]
大兄弟，改个地址吧，自己新建一个服务吧。字段就这几个。不难的哦。
![image](https://user-images.githubusercontent.com/25259066/70019386-0af7b280-15c4-11ea-882b-4c96e9a76ec9.png)

**Comment by liangwei0101** [comment]
大兄弟，随便新增一个随便后端服务吧，字段返回三个就好了，int no、String name、String email 这三个。
